### DISCUSSION TITLE
schema out of wasm

### DISCUSSION THREAD

**Discussion by dzmitry-lahoda** [informalsystems/ibc-rs#1002] [General]
Both polkadot-sdk(for scale) and cosmwasm(for json) allow not to compile schema into wasm32 binary (size matters).

May be solana borsch does same? 

I just was hit with limit of contract upload, and doing not(target_arch = wasm32) for building metadata into wasm.

So what is best way if any to express it agains ibc-rs?

Can feature switch be on/off depending on target in calling crate? Like MyCWContract can enable and disable JSON schema depending on target?

```toml
borsh       = { workspace = true, optional = true }
derive_more = { workspace = true }
displaydoc  = { workspace = true }
prost       = { workspace = true }
schemars    = { workspace = true, optional = true }
serde       = { workspace = true, optional = true }
time        = { workspace = true }

# ibc dependencies
ibc-proto = { workspace = true }

# cosmos dependencies
tendermint = { workspace = true }

# parity dependencies
parity-scale-codec  = { workspace = true, optional = true }
scale-info          = { workspace = true, optional = true }
```
