### ISSUE TITLE
ICS20 token denomination not according to specs

### ISSUE THREAD

**Issue by mpoke** [informalsystems/ibc-rs#1564]
## Summary of Bug

The denomination of a transferred token using 
```
hermes tx raw ft-transfer ibc-1 ibc-0 transfer channel-0 9999 -o 1000 -n 1 -d samoleans
```
does not follow the structure defined in [ICS 020](https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures). It should be `transfer/channel-1/samoleans`, but instead it is
```
gaiad --node tcp://localhost:26557 query bank balances $(gaiad --home data/ibc-1 keys --keyring-backend="test" show user -a)
balances:
- amount: "9999"
  denom: ibc/C1840BD16FCFA8F421DAA0DAAB08B9C323FC7685D0D7951DC37B3F9ECB08A199
- amount: "100000000000"
  denom: samoleans
- amount: "99999998917"
  denom: stake
pagination:
  next_key: null
  total: "0"
```

## Version
v0.8.0

## Steps to Reproduce

Follow the [Hermes tutorial](https://hermes.informal.systems/tutorials/local-chains/index.html).

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
