### ISSUE TITLE
Evmos bech32 prefix is not detected

### ISSUE THREAD

**Issue by arnabghose997** [informalsystems/ibc-rs#1785]
## Summary of Bug

As you might have heard that Ethermint have changed their name to EVMOS, this might be causing an issue while I was trying to establish an IBC path locally between Gaia and Evmos as the Bech32 prefix for EVMOS is `evmos`. Following is the log for reference:

```
$ hermes start
The Hermes configuration file at path '~/.hermes/config.toml' is invalid, reason: parse error: unknown variant `evmos`, expected `cosmos` or `ethermint` for key `chains.address_type` at line 251 column 31
```

## Version

Version: v0.10.0

## Steps to Reproduce

There needs to be a replacement of `ethermint` bech32 address prefix with `evmos`

## Acceptance Criteria

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
This codepath in Hermes hasn't been tested in months (since #1295), thank you for highlighting the problem!

I prepared a quick dev branch for you to give it a try, seems like the most important change is just renaming some variables: https://github.com/informalsystems/ibc-rs/tree/1785_evmos

Can you let us know if this works?

**Comment by arnabghose997** [comment]
Hey @adizere, thanks for the update. I will need some time to test it out. Will post my update here soon.

**Comment by arnabghose997** [comment]
HI @adizere , below are my observations:

### Oberservations from running both Gaia and Evmos chain

Both Gaia and Evmos chains were run using the `starport`. Below are their `config.yml` configuration:

Gaia:

```yaml
accounts:
  - name: akash
    coins: ["10000000000000uatom", "100000000stake"]
  - name: badal
    coins: ["50000000000uatom"]
validator:
  name: akash
  staked: "1000000stake"
host:
  rpc: ":26657"
  p2p: ":26656"
  prof: ":6061"
  grpc: ":9095"
  grpc-web: ":9093"
  api: ":1318"
  frontend: ":8081"
  dev-ui: ":12346"
faucet:
  name: badal 
  coins: ["100000uatom"]
  port: 4500
build:
  binary: "gaiad"
init:
  home: "home/arnab/.gaia"
genesis:
  chain_id: "localcosmos-1"
```

Evmos:

```yaml
accounts:
  - name: alice
    coins: ["100000000stake", "100000000000000000000aevmos"]
  - name: bob
    coins: ["5000000000000aevmos"]
validator:
  name: alice
  staked: "100000000000000000000aevmos"
host:
  rpc: ":36657"
  p2p: ":36656"
  prof: ":7061"
  grpc: ":10095"
  grpc-web: ":10093"
  api: ":2318"
  frontend: ":9081"
  dev-ui: ":22346"
faucet:
  name: bob 
  coins: ["100000aevmos"]
  port: 4501
build:
  binary: "evmosd"
init:
  home: "$HOME/.evmosd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "evmosd_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "aevmos"
    mint:
      params:
        mint_denom: "aevmos"
    crisis:
      constant_fee:
        denom: "aevmos"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aevmos"
    evm:
      params:
        evm_denom: "aevmos"
```

Account `badal` from `gaiad`, and `bob` from `evmos` were chosen to be the relayer accounts. So we will focus on them

When both chains were started, the mnemonics of `badal` and `bob` were noted as follows:

`badal`:

```bash
[GAIA DAEMON] cosmos16xv7mzk9gffqs28wxq9etdsz083af7jxhzu2xt
[STARPORT] 🙂 Created account "badal" with address "cosmos16xv7mzk9gffqs28wxq9etdsz083af7jxhzu2xt" with mnemonic: "path oak treat put saddle quarter uniform broom aunt text cotton slice hotel mention dwarf prosper prepare buffalo still alone sweet lesson worth gentle"
```

 `bob`:

```bash
[EVMOS DAEMON] evmos147h9vvlhxxe8nhjgaadraeu93rv9xv36dvfv0v
[STARPORT] 🙂 Created account "bob" with address "evmos147h9vvlhxxe8nhjgaadraeu93rv9xv36dvfv0v" with mnemonic: "scissors crouch hair bacon magnet analyst drip scare palace tragic verify forget have census blame best rabbit buzz hip whale define also october flag"
```

Now while trying to use the hermes CLI to restore the account addresses through following comand:

```bash
$ hermes keys restore --mnemonic <account-mnemonic> <chain-id>
```

Account address of `badal` (`Gaia` chain) was imported exactly how its supposed to be. But the account address of `bob` (`Evmos` chain) was different.

- Account address of `bob` when starting the chain with starport: `evmos147h9vvlhxxe8nhjgaadraeu93rv9xv36dvfv0v`
- Account address of `bob` after the mnemonic import through hermes CLI: `evmos1e5qlekdtkqwud53dtdau9pqxttempkdzxwd8nw`

The public key type of Evmos is `/ethermint.crypto.v1.ethsecp256k1.PubKey`. It seems that version of Public key type defined in Evmos could be different from what is defined in Hermes.
