### ISSUE TITLE
Support no_std without `[patch.crates-io]` section

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-rs#1858]
## Crate

`ibc`, `ibc-proto`

## Summary

With #1846 merged, the `ibc` and `ibc-proto` crates on master branch now fully support no_std. There are just two dependencies that need to be patched for no_std to fully work:

- [x] Wait for new version of `tendermint-rs` to be released so that https://github.com/informalsystems/tendermint-rs/pull/1087 is included.
- [x] Wait for the [merge request for `safe-regex`](https://gitlab.com/leonhard-llc/safe-regex-rs/-/merge_requests/1) to be merged and published.
  - PR: #1866

As of now, developers who need full no_std support can include the following section in their project `Cargo.toml`:

```toml
[patch.crates-io]
tendermint                        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-proto                  = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
tendermint-light-client-verifier  = { git = "https://github.com/informalsystems/tendermint-rs", branch = "v0.23.x" }
```

## Acceptance Criteria
 
This issue will be closed when new version of ibc-rs is released, and no_std us supported without requiring the `[patch.crates-io]` section.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
