### ISSUE TITLE
Support for Interchain accounts filtering policy

### ISSUE THREAD

**Issue by adizere** [informalsystems/ibc-rs#1927]
We should add an option in the `mode.packets` section of config.toml that toggles on/off relaying of packets that are related to Interchain accounts.

**Comment by romac** [comment]
This has been implemented by adding support for wildcards in the packet filter config, eg. to only relay on `channel-0` and on all ICA channels:

```toml
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-0'],
]
```
