### ISSUE TITLE
Use of system clock time to determine client state

### ISSUE THREAD

**Issue by faddat** [informalsystems/ibc-rs#2180]
## Summary of Bug

The osmo client on evmos is live, but hermes uses the time of the computer running it to determine frozen/expiry:

Client state:

```yaml
client_state:
  '@type': /ibc.lightclients.tendermint.v1.ClientState
  allow_update_after_expiry: true
  allow_update_after_misbehaviour: true
  chain_id: osmosis-1
  frozen_height:
    revision_height: "0"
    revision_number: "0"
  latest_height:
    revision_height: "3484087"
    revision_number: "1"
  max_clock_drift: 25s
  proof_specs:
  - inner_spec:
      child_order:
      - 0
      - 1
      child_size: 33
      empty_child: null
      hash: SHA256
      max_prefix_length: 12
      min_prefix_length: 4
    leaf_spec:
      hash: SHA256
      length: VAR_PROTO
      prefix: AA==
      prehash_key: NO_HASH
      prehash_value: SHA256
    max_depth: 0
    min_depth: 0
  - inner_spec:
      child_order:
      - 0
      - 1
      child_size: 32
      empty_child: null
      hash: SHA256
      max_prefix_length: 1
      min_prefix_length: 1
    leaf_spec:
      hash: SHA256
      length: VAR_PROTO
      prefix: AA==
      prehash_key: NO_HASH
      prehash_value: SHA256
    max_depth: 0
    min_depth: 0
  trust_level:
    denominator: "3"
    numerator: "1"
  trusting_period: 864000s
  unbonding_period: 1209600s
```

**when we try to relay**

```
  - Client: 07-tendermint-0
    * Connection: connection-0
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-0
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-204
# Chain: osmosis-1
  - Client: 07-tendermint-1566
  - Client: 07-tendermint-1674
  - Client: 07-tendermint-1840
    * Connection: connection-1440
      | State: OPEN
      | Counterparty state: OPEN
      + Channel: channel-204
        | Port: transfer
        | State: OPEN
        | Counterparty: channel-0
  - Client: 07-tendermint-1924
  - Client: 07-tendermint-1925
```

**when we try to do a very important client update**

```
hermes tx raw update-client evmos_9001-2 07-tendermint-0
2022-05-04T12:52:51.025718Z  INFO ThreadId(01) using default configuration from '/Users/faddat/.hermes/config.toml'
Error: foreign client error: client 07-tendermint-0 on chain id evmos_9001-2 is expired or frozen: expired: time elapsed since last client update: Some(5067688.495405272s)
```

Therefore, we should not check the time on my computer when attempting a client update.

## Version

460eb0c63f8ae1b7b1b204eda49c3c6b19b18452
f2937bc1 <- master branch just now

## Steps to Reproduce

Query the state of the osmosis client on evmos, note that the client is not expired or frozen.

Use hermes to try to relay between osmosis and evmos.  Hermes will report that the osmosis client on evmos is expired or frozen.

## Acceptance Criteria

Hermes should not be concerned with time on my computer when relaying because each chain has its own sense of time.  When evmos went down, it did not experience the passage of time.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
